name: Azure Blob Deploy

on: [push]

jobs:
  azure_blob_deploy:
    runs-on: ubuntu-latest
    name: Azure Blob Dploy
    steps:
      - uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'

      - name: install
        run: npm install

      - name: install
        run: npm run generate

      - name: AzureLogin
        uses: Azure/github-actions/login@master
        env:
          AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
          AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
          AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: AzureDeployToStaticWebsite
        uses: planethouki/github-actions/storage-blob-static-website@master
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          SAS_TOKEN: ${{ secrets.SAS_TOKEN }}
          PUBLIC_FOLDER: dist
